# Generated by Django 6.0.5 on 2026-05-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalhistory",
            name="diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="doctor_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="lab_result_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="prescription_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="allergies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="current_medications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="disease_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="previous_surgeries",
            field=models.TextField(blank=True, null=True),
        ),
    ]
