# Generated by Django 6.0.5 on 2026-05-26 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_hospital_doctorprofile_hospital"),
        (
            "appointments",
            "0002_medicalhistory_diagnosis_medicalhistory_doctor_notes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.TextField(blank=True, null=True)),
                ("medicine_name", models.CharField(max_length=255)),
                ("dosage", models.CharField(max_length=255)),
                ("frequency", models.CharField(max_length=255)),
                ("duration", models.CharField(max_length=255)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appointments.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.patientprofile",
                    ),
                ),
            ],
        ),
    ]
