# Generated by Django 6.0.5 on 2026-05-28 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_hospital_doctorprofile_hospital"),
        ("appointments", "0003_prescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("Lab Report", "Lab Report"),
                            ("Prescription", "Prescription"),
                            ("Discharge Summary", "Discharge Summary"),
                            ("X-Ray", "X-Ray"),
                            ("MRI", "MRI"),
                            ("CT Scan", "CT Scan"),
                            ("Blood Test", "Blood Test"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("file", models.FileField(upload_to="medical_documents/")),
                ("description", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.patientprofile",
                    ),
                ),
            ],
        ),
    ]
